admin_users	id	integer
admin_users	username	character varying
admin_users	password_hash	character varying
admin_users	nombre	character varying
admin_users	activo	boolean
admin_users	creado_en	timestamp without time zone
admin_users	actualizado_en	timestamp without time zone
alertas_inventario	id_alerta	integer
alertas_inventario	id_producto	integer
alertas_inventario	id_lote	integer
alertas_inventario	tipo_alerta	character varying
alertas_inventario	mensaje	text
alertas_inventario	nivel_urgencia	character varying
alertas_inventario	resuelta	boolean
alertas_inventario	fecha_creacion	timestamp without time zone
alertas_inventario	fecha_resolucion	timestamp without time zone
alertas_inventario	id_restaurante	integer
alertas_limites	id_alerta	integer
alertas_limites	id_restaurante	integer
alertas_limites	id_plan	integer
alertas_limites	tipo_alerta	character varying
alertas_limites	recurso	character varying
alertas_limites	valor_actual	integer
alertas_limites	valor_limite	integer
alertas_limites	porcentaje_uso	numeric
alertas_limites	estado	character varying
alertas_limites	fecha_alerta	timestamp without time zone
alertas_limites	fecha_resolucion	timestamp without time zone
alertas_limites	mensaje	text
alertas_limites	datos_adicionales	jsonb
archivos_egresos	id_archivo	integer
archivos_egresos	id_egreso	integer
archivos_egresos	nombre_archivo	character varying
archivos_egresos	ruta_archivo	character varying
archivos_egresos	tipo_archivo	character varying
archivos_egresos	tamaño_archivo	integer
archivos_egresos	subido_por	integer
archivos_egresos	fecha_subida	timestamp without time zone
arqueos_caja	id_arqueo	integer
arqueos_caja	id_restaurante	integer
arqueos_caja	id_sucursal	integer
arqueos_caja	id_vendedor	integer
arqueos_caja	monto_inicial	numeric
arqueos_caja	fecha_apertura	timestamp without time zone
arqueos_caja	monto_final	numeric
arqueos_caja	fecha_cierre	timestamp without time zone
arqueos_caja	diferencia	numeric
arqueos_caja	estado	character varying
arqueos_caja	observaciones	text
auditoria_admin	id_auditoria	integer
auditoria_admin	id_usuario	integer
auditoria_admin	accion	character varying
auditoria_admin	tabla_afectada	character varying
auditoria_admin	id_registro	integer
auditoria_admin	datos_anteriores	jsonb
auditoria_admin	datos_nuevos	jsonb
auditoria_admin	fecha_accion	timestamp without time zone
auditoria_planes	id_auditoria	integer
auditoria_planes	id_restaurante	integer
auditoria_planes	id_plan_anterior	integer
auditoria_planes	id_plan_nuevo	integer
auditoria_planes	tipo_cambio	character varying
auditoria_planes	motivo	text
auditoria_planes	id_usuario_cambio	integer
auditoria_planes	nombre_usuario	character varying
auditoria_planes	fecha_cambio	timestamp without time zone
auditoria_planes	fecha_efectiva	date
auditoria_planes	datos_adicionales	jsonb
auditoria_pos	id_auditoria	bigint
auditoria_pos	id_vendedor	integer
auditoria_pos	accion	character varying
auditoria_pos	tabla_afectada	character varying
auditoria_pos	id_registro	bigint
auditoria_pos	datos_anteriores	jsonb
auditoria_pos	datos_nuevos	jsonb
auditoria_pos	fecha_accion	timestamp with time zone
auditoria_pos	id_restaurante	integer
auditoria_pos	ip_origen	inet
auditoria_pos	user_agent	character varying
auditoria_pos	descripcion	text
auditoria_pos	exito	boolean
auditoria_pos	error_msg	text
casos_exito	id	integer
casos_exito	nombre_restaurante	character varying
casos_exito	logo_url	character varying
casos_exito	tipo_restaurante	character varying
casos_exito	ciudad	character varying
casos_exito	sucursales	integer
casos_exito	tiempo_uso_meses	integer
casos_exito	testimonio	text
casos_exito	nombre_contacto	character varying
casos_exito	cargo_contacto	character varying
casos_exito	foto_contacto	character varying
casos_exito	video_testimonio	character varying
casos_exito	metricas_antes	jsonb
casos_exito	metricas_despues	jsonb
casos_exito	mejoras_especificas	ARRAY
casos_exito	plan_contratado	character varying
casos_exito	fecha_implementacion	date
casos_exito	activo	boolean
casos_exito	destacado	boolean
casos_exito	orden_display	integer
casos_exito	created_at	timestamp without time zone
casos_exito	updated_at	timestamp without time zone
categorias	id_categoria	integer
categorias	nombre	character varying
categorias	activo	boolean
categorias	created_at	timestamp without time zone
categorias	id_restaurante	integer
categorias_almacen	id_categoria_almacen	integer
categorias_almacen	nombre	character varying
categorias_almacen	descripcion	text
categorias_almacen	tipo_almacen	character varying
categorias_almacen	condiciones_especiales	text
categorias_almacen	rotacion_recomendada	character varying
categorias_almacen	id_restaurante	integer
categorias_almacen	activo	boolean
categorias_almacen	created_at	timestamp without time zone
categorias_almacen	updated_at	timestamp without time zone
categorias_egresos	id_categoria_egreso	integer
categorias_egresos	nombre	character varying
categorias_egresos	descripcion	text
categorias_egresos	color	character varying
categorias_egresos	icono	character varying
categorias_egresos	activo	boolean
categorias_egresos	id_restaurante	integer
categorias_egresos	created_at	timestamp without time zone
categorias_egresos	updated_at	timestamp without time zone
clientes	id_cliente	integer
clientes	nombre	character varying
clientes	telefono	character varying
clientes	email	character varying
clientes	fecha_registro	timestamp without time zone
configuracion_web	id	integer
configuracion_web	clave	character varying
configuracion_web	valor	text
configuracion_web	descripcion	text
configuracion_web	tipo	character varying
configuracion_web	seccion	character varying
configuracion_web	created_at	timestamp without time zone
configuracion_web	updated_at	timestamp without time zone
configuraciones_restaurante	id_config	integer
configuraciones_restaurante	id_restaurante	integer
configuraciones_restaurante	clave_config	text
configuraciones_restaurante	valor_config	jsonb
configuraciones_sistema	clave_config	character varying
configuraciones_sistema	valor_config	jsonb
configuraciones_sistema	creado_en	timestamp without time zone
configuraciones_sistema	actualizado_en	timestamp without time zone
contenido_web	id	integer
contenido_web	titulo	character varying
contenido_web	slug	character varying
contenido_web	contenido	text
contenido_web	resumen	text
contenido_web	imagen_portada	character varying
contenido_web	tipo_contenido	character varying
contenido_web	autor	character varying
contenido_web	tags	ARRAY
contenido_web	estado	character varying
contenido_web	fecha_publicacion	timestamp without time zone
contenido_web	fecha_modificacion	timestamp without time zone
contenido_web	meta_title	character varying
contenido_web	meta_description	text
contenido_web	created_at	timestamp without time zone
contenido_web	updated_at	timestamp without time zone
conversion_events	id	integer
conversion_events	event_type	character varying
conversion_events	timestamp	timestamp without time zone
conversion_events	plan_name	character varying
conversion_events	user_agent	text
conversion_events	referrer	text
conversion_events	session_id	character varying
conversion_events	ip_address	inet
conversion_events	metadata	jsonb
conversion_events	created_at	timestamp without time zone
demos_reuniones	id	integer
demos_reuniones	lead_id	integer
demos_reuniones	tipo_reunion	character varying
demos_reuniones	fecha_programada	timestamp without time zone
demos_reuniones	duracion_minutos	integer
demos_reuniones	plataforma	character varying
demos_reuniones	link_reunion	character varying
demos_reuniones	estado	character varying
demos_reuniones	notas_pre_reunion	text
demos_reuniones	notas_post_reunion	text
demos_reuniones	resultado	character varying
demos_reuniones	proximo_seguimiento	timestamp without time zone
demos_reuniones	created_at	timestamp without time zone
demos_reuniones	updated_at	timestamp without time zone
detalle_ventas	id_detalle	integer
detalle_ventas	id_venta	integer
detalle_ventas	id_producto	integer
detalle_ventas	cantidad	integer
detalle_ventas	precio_unitario	numeric
detalle_ventas	subtotal	numeric
detalle_ventas	observaciones	text
detalle_ventas	created_at	timestamp without time zone
detalle_ventas	id_restaurante	integer
detalle_ventas_modificadores	id_detalle_venta	integer
detalle_ventas_modificadores	id_modificador	integer
detalle_ventas_modificadores	precio_aplicado	numeric
detalle_ventas_modificadores	created_at	timestamp without time zone
dim_tiempo	id_tiempo	integer
dim_tiempo	fecha	date
dim_tiempo	dia	integer
dim_tiempo	mes	integer
dim_tiempo	anio	integer
dim_tiempo	nombre_mes	character varying
dim_tiempo	nombre_dia	character varying
dim_tiempo	es_fin_de_semana	boolean
dim_tiempo	turno	character varying
egresos	id_egreso	integer
egresos	concepto	character varying
egresos	descripcion	text
egresos	monto	numeric
egresos	fecha_egreso	date
egresos	id_categoria_egreso	integer
egresos	metodo_pago	character varying
egresos	proveedor_nombre	character varying
egresos	proveedor_documento	character varying
egresos	proveedor_telefono	character varying
egresos	proveedor_email	character varying
egresos	numero_factura	character varying
egresos	numero_recibo	character varying
egresos	numero_comprobante	character varying
egresos	estado	character varying
egresos	requiere_aprobacion	boolean
egresos	aprobado_por	integer
egresos	fecha_aprobacion	timestamp without time zone
egresos	comentario_aprobacion	text
egresos	es_deducible	boolean
egresos	numero_autorizacion_fiscal	character varying
egresos	codigo_control	character varying
egresos	es_recurrente	boolean
egresos	frecuencia_recurrencia	character varying
egresos	proxima_fecha_recurrencia	date
egresos	archivos_adjuntos	jsonb
egresos	registrado_por	integer
egresos	id_sucursal	integer
egresos	id_restaurante	integer
egresos	created_at	timestamp without time zone
egresos	updated_at	timestamp without time zone
facturas	id_factura	integer
facturas	numero	character varying
facturas	nit_cliente	character varying
facturas	razon_social	character varying
facturas	total	numeric
facturas	fecha	timestamp without time zone
facturas	id_venta	integer
flujo_aprobaciones_egresos	id_flujo	integer
flujo_aprobaciones_egresos	id_egreso	integer
flujo_aprobaciones_egresos	id_vendedor	integer
flujo_aprobaciones_egresos	accion	character varying
flujo_aprobaciones_egresos	comentario	text
flujo_aprobaciones_egresos	fecha_accion	timestamp without time zone
grupos_mesas	id_grupo_mesa	integer
grupos_mesas	id_restaurante	integer
grupos_mesas	id_sucursal	integer
grupos_mesas	id_venta_principal	integer
grupos_mesas	estado	character varying
grupos_mesas	created_at	timestamp without time zone
grupos_mesas	updated_at	timestamp without time zone
grupos_mesas	id_mesero	integer
historial_pagos_diferidos	id_historial	integer
historial_pagos_diferidos	id_pago_diferido	integer
historial_pagos_diferidos	id_venta	integer
historial_pagos_diferidos	id_pago_final	integer
historial_pagos_diferidos	monto_pagado	numeric
historial_pagos_diferidos	fecha_pago	timestamp without time zone
historial_pagos_diferidos	id_vendedor	integer
historial_pagos_diferidos	observaciones	text
historial_pagos_diferidos	id_restaurante	integer
historial_pagos_diferidos	created_at	timestamp without time zone
historial_pagos_diferidos	procesado_por	integer
integrity_logs	id	integer
integrity_logs	check_name	character varying
integrity_logs	status	character varying
integrity_logs	message	text
integrity_logs	details_count	integer
integrity_logs	execution_time_ms	integer
integrity_logs	created_at	timestamp without time zone
inventario_lotes	id_lote	integer
inventario_lotes	id_producto	integer
inventario_lotes	numero_lote	character varying
inventario_lotes	cantidad_inicial	numeric
inventario_lotes	cantidad_actual	numeric
inventario_lotes	fecha_fabricacion	date
inventario_lotes	fecha_caducidad	date
inventario_lotes	precio_compra	numeric
inventario_lotes	activo	boolean
inventario_lotes	id_restaurante	integer
inventario_lotes	created_at	timestamp without time zone
inventario_lotes	updated_at	timestamp without time zone
inventario_lotes	id_categoria_almacen	integer
inventario_lotes	ubicacion_especifica	character varying
inventario_lotes	proveedor	character varying
inventario_lotes	certificacion_organica	boolean
leads_prospectos	id	integer
leads_prospectos	nombre	character varying
leads_prospectos	email	character varying
leads_prospectos	telefono	character varying
leads_prospectos	nombre_restaurante	character varying
leads_prospectos	tipo_restaurante	character varying
leads_prospectos	num_sucursales	integer
leads_prospectos	num_empleados	integer
leads_prospectos	ciudad	character varying
leads_prospectos	pais	character varying
leads_prospectos	fuente_lead	character varying
leads_prospectos	estado	character varying
leads_prospectos	interes_plan_id	integer
leads_prospectos	notas	text
leads_prospectos	fecha_contacto	timestamp without time zone
leads_prospectos	fecha_demo	timestamp without time zone
leads_prospectos	vendedor_asignado	character varying
leads_prospectos	created_at	timestamp without time zone
leads_prospectos	updated_at	timestamp without time zone
mesas	id_mesa	integer
mesas	numero	integer
mesas	id_sucursal	integer
mesas	capacidad	integer
mesas	estado	character varying
mesas	id_venta_actual	integer
mesas	hora_apertura	timestamp without time zone
mesas	hora_cierre	timestamp without time zone
mesas	total_acumulado	numeric
mesas	created_at	timestamp without time zone
mesas	updated_at	timestamp without time zone
mesas	id_restaurante	integer
mesas	id_mesero_actual	integer
mesas	id_grupo_mesa	integer
mesas_en_grupo	id_mesa_en_grupo	integer
mesas_en_grupo	id_grupo_mesa	integer
mesas_en_grupo	id_mesa	integer
mesas_en_grupo	created_at	timestamp without time zone
metodos_pago	id_pago	integer
metodos_pago	descripcion	character varying
metodos_pago	activo	boolean
metodos_pago	created_at	timestamp without time zone
metodos_pago	updated_at	timestamp without time zone
metodos_pago_backup	id_pago	integer
metodos_pago_backup	descripcion	character varying
metodos_pago_backup	activo	boolean
metodos_pago_backup	id_restaurante	integer
metricas_web	id	integer
metricas_web	fecha	date
metricas_web	tipo_metrica	character varying
metricas_web	valor	integer
metricas_web	fuente	character varying
metricas_web	pagina	character varying
metricas_web	created_at	timestamp without time zone
migrations	id	integer
migrations	migration_name	character varying
migrations	executed_at	timestamp without time zone
migrations	description	text
migrations	status	character varying
movimientos_inventario	id_movimiento	integer
movimientos_inventario	id_producto	integer
movimientos_inventario	tipo_movimiento	character varying
movimientos_inventario	cantidad	integer
movimientos_inventario	stock_anterior	integer
movimientos_inventario	stock_actual	integer
movimientos_inventario	fecha_movimiento	timestamp with time zone
movimientos_inventario	id_vendedor	integer
movimientos_inventario	id_restaurante	integer
movimientos_inventario	id_lote	integer
movimientos_inventario	id_categoria_almacen	integer
movimientos_inventario	motivo	text
newsletter_suscriptores	id	integer
newsletter_suscriptores	email	character varying
newsletter_suscriptores	nombre	character varying
newsletter_suscriptores	estado	character varying
newsletter_suscriptores	fecha_suscripcion	timestamp without time zone
newsletter_suscriptores	fecha_baja	timestamp without time zone
newsletter_suscriptores	fuente	character varying
newsletter_suscriptores	ip_address	inet
newsletter_suscriptores	user_agent	text
newsletter_suscriptores	created_at	timestamp without time zone
newsletter_suscriptores	updated_at	timestamp without time zone
pagos_diferidos	id_pago_diferido	integer
pagos_diferidos	id_venta	integer
pagos_diferidos	id_mesa	integer
pagos_diferidos	total_pendiente	numeric
pagos_diferidos	fecha_creacion	timestamp without time zone
pagos_diferidos	fecha_vencimiento	timestamp without time zone
pagos_diferidos	estado	character varying
pagos_diferidos	observaciones	text
pagos_diferidos	id_restaurante	integer
pagos_diferidos	created_at	timestamp without time zone
pagos_diferidos	updated_at	timestamp without time zone
pagos_restaurantes	id	integer
pagos_restaurantes	id_restaurante	integer
pagos_restaurantes	monto	numeric
pagos_restaurantes	fecha_pago	timestamp without time zone
pagos_restaurantes	metodo_pago	character varying
pagos_restaurantes	observaciones	text
pagos_restaurantes	registrado_por	integer
pagos_restaurantes	creado_en	timestamp without time zone
planes	id_plan	integer
planes	nombre	character varying
planes	descripcion	text
planes	precio_mensual	numeric
planes	precio_anual	numeric
planes	max_sucursales	integer
planes	max_usuarios	integer
planes	max_productos	integer
planes	max_transacciones_mes	integer
planes	almacenamiento_gb	integer
planes	funcionalidades	jsonb
planes	activo	boolean
planes	orden_display	integer
planes	created_at	timestamp without time zone
planes	updated_at	timestamp without time zone
planes_pos	id	integer
planes_pos	nombre	character varying
planes_pos	descripcion	text
planes_pos	precio_mensual	numeric
planes_pos	precio_anual	numeric
planes_pos	caracteristicas	jsonb
planes_pos	max_sucursales	integer
planes_pos	max_usuarios	integer
planes_pos	incluye_impresion	boolean
planes_pos	incluye_delivery	boolean
planes_pos	incluye_reservas	boolean
planes_pos	incluye_analytics	boolean
planes_pos	incluye_soporte_24h	boolean
planes_pos	activo	boolean
planes_pos	orden_display	integer
planes_pos	created_at	timestamp without time zone
planes_pos	updated_at	timestamp without time zone
prefacturas	id_prefactura	integer
prefacturas	id_mesa	integer
prefacturas	id_venta_principal	integer
prefacturas	total_acumulado	numeric
prefacturas	estado	character varying
prefacturas	fecha_apertura	timestamp without time zone
prefacturas	fecha_cierre	timestamp without time zone
prefacturas	observaciones	text
prefacturas	created_at	timestamp without time zone
prefacturas	id_restaurante	integer
presupuestos_egresos	id_presupuesto	integer
presupuestos_egresos	anio	integer
presupuestos_egresos	mes	integer
presupuestos_egresos	id_categoria_egreso	integer
presupuestos_egresos	monto_presupuestado	numeric
presupuestos_egresos	monto_gastado	numeric
presupuestos_egresos	activo	boolean
presupuestos_egresos	id_restaurante	integer
presupuestos_egresos	created_at	timestamp without time zone
presupuestos_egresos	updated_at	timestamp without time zone
productos	id_producto	integer
productos	nombre	character varying
productos	precio	numeric
productos	id_categoria	integer
productos	stock_actual	integer
productos	activo	boolean
productos	imagen_url	text
productos	created_at	timestamp without time zone
productos	id_restaurante	integer
productos_modificadores	id_modificador	integer
productos_modificadores	id_producto	integer
productos_modificadores	nombre_modificador	character varying
productos_modificadores	precio_extra	numeric
productos_modificadores	tipo_modificador	character varying
productos_modificadores	activo	boolean
productos_modificadores	created_at	timestamp without time zone
productos_modificadores	updated_at	timestamp without time zone
promociones	id_promocion	integer
promociones	nombre	character varying
promociones	tipo	character varying
promociones	valor	numeric
promociones	fecha_inicio	date
promociones	fecha_fin	date
promociones	id_producto	integer
promociones	creada_en	timestamp without time zone
promociones	activa	boolean
promociones	id_restaurante	integer
promociones_sucursales	id_relacion	integer
promociones_sucursales	id_promocion	integer
promociones_sucursales	id_sucursal	integer
promociones_sucursales	aplicada_en	timestamp without time zone
reservas	id_reserva	integer
reservas	id_restaurante	integer
reservas	id_sucursal	integer
reservas	id_mesa	integer
reservas	id_cliente	integer
reservas	nombre_cliente	character varying
reservas	telefono_cliente	character varying
reservas	email_cliente	character varying
reservas	fecha_hora_inicio	timestamp with time zone
reservas	fecha_hora_fin	timestamp with time zone
reservas	numero_personas	integer
reservas	estado	character varying
reservas	observaciones	text
reservas	created_at	timestamp without time zone
reservas	updated_at	timestamp without time zone
reservas	registrado_por	integer
restaurantes	id_restaurante	integer
restaurantes	nombre	character varying
restaurantes	direccion	text
restaurantes	ciudad	character varying
restaurantes	telefono	character varying
restaurantes	email	character varying
restaurantes	activo	boolean
restaurantes	created_at	timestamp without time zone
roles_admin	id_rol	integer
roles_admin	nombre	character varying
roles_admin	descripcion	character varying
roles_admin	permisos	jsonb
roles_admin	creado_en	timestamp without time zone
servicios_restaurante	id	integer
servicios_restaurante	id_restaurante	integer
servicios_restaurante	nombre_plan	character varying
servicios_restaurante	descripcion_plan	text
servicios_restaurante	fecha_inicio	date
servicios_restaurante	fecha_fin	date
servicios_restaurante	estado_suscripcion	character varying
servicios_restaurante	precio_mensual	numeric
servicios_restaurante	ultimo_pago	date
servicios_restaurante	funcionalidades_json	jsonb
servicios_restaurante	creado_en	timestamp with time zone
servicios_restaurante	actualizado_en	timestamp with time zone
solicitudes_demo	id_solicitud	integer
solicitudes_demo	nombre	character varying
solicitudes_demo	email	character varying
solicitudes_demo	telefono	character varying
solicitudes_demo	restaurante	character varying
solicitudes_demo	plan_interes	character varying
solicitudes_demo	tipo_negocio	character varying
solicitudes_demo	mensaje	text
solicitudes_demo	horario_preferido	character varying
solicitudes_demo	estado	character varying
solicitudes_demo	fecha_solicitud	timestamp without time zone
solicitudes_demo	ip_address	inet
solicitudes_demo	user_agent	text
solicitudes_demo	procesado_por	integer
solicitudes_demo	fecha_procesamiento	timestamp without time zone
solicitudes_demo	observaciones	text
solicitudes_demo	created_at	timestamp without time zone
solicitudes_demo	updated_at	timestamp without time zone
soporte_tickets	id_ticket	integer
soporte_tickets	id_vendedor	integer
soporte_tickets	id_restaurante	integer
soporte_tickets	asunto	character varying
soporte_tickets	descripcion	text
soporte_tickets	estado	character varying
soporte_tickets	fecha_creacion	timestamp without time zone
soporte_tickets	fecha_resuelto	timestamp without time zone
soporte_tickets	respuesta	text
sucursales	id_sucursal	integer
sucursales	nombre	character varying
sucursales	ciudad	character varying
sucursales	direccion	text
sucursales	activo	boolean
sucursales	created_at	timestamp without time zone
sucursales	id_restaurante	integer
suscripciones	id_suscripcion	integer
suscripciones	id_restaurante	integer
suscripciones	id_plan	integer
suscripciones	estado	character varying
suscripciones	fecha_inicio	date
suscripciones	fecha_fin	date
suscripciones	fecha_renovacion	date
suscripciones	metodo_pago	character varying
suscripciones	ultimo_pago	timestamp without time zone
suscripciones	proximo_pago	timestamp without time zone
suscripciones	auto_renovacion	boolean
suscripciones	notificaciones_email	boolean
suscripciones	created_at	timestamp without time zone
suscripciones	updated_at	timestamp without time zone
system_tasks	id	integer
system_tasks	task_name	character varying
system_tasks	last_run	timestamp without time zone
system_tasks	next_run	timestamp without time zone
system_tasks	interval_minutes	integer
system_tasks	is_active	boolean
system_tasks	created_at	timestamp without time zone
testimonios_web	id	integer
testimonios_web	nombre	character varying
testimonios_web	cargo	character varying
testimonios_web	empresa	character varying
testimonios_web	foto_url	character varying
testimonios_web	testimonio	text
testimonios_web	calificacion	integer
testimonios_web	ciudad	character varying
testimonios_web	fecha_experiencia	date
testimonios_web	plan_contratado	character varying
testimonios_web	tiempo_uso_meses	integer
testimonios_web	activo	boolean
testimonios_web	destacado	boolean
testimonios_web	orden_display	integer
testimonios_web	created_at	timestamp without time zone
testimonios_web	updated_at	timestamp without time zone
transferencias_almacen	id_transferencia	integer
transferencias_almacen	id_producto	integer
transferencias_almacen	id_lote	integer
transferencias_almacen	cantidad_transferida	numeric
transferencias_almacen	almacen_origen	integer
transferencias_almacen	almacen_destino	integer
transferencias_almacen	motivo	character varying
transferencias_almacen	id_responsable	integer
transferencias_almacen	fecha_transferencia	timestamp without time zone
transferencias_almacen	estado	character varying
transferencias_almacen	id_restaurante	integer
user_sessions	id	integer
user_sessions	session_id	character varying
user_sessions	ip_address	inet
user_sessions	user_agent	text
user_sessions	referrer	text
user_sessions	landing_page	character varying
user_sessions	utm_source	character varying
user_sessions	utm_medium	character varying
user_sessions	utm_campaign	character varying
user_sessions	utm_term	character varying
user_sessions	utm_content	character varying
user_sessions	country	character varying
user_sessions	city	character varying
user_sessions	device_type	character varying
user_sessions	browser	character varying
user_sessions	os	character varying
user_sessions	first_visit	timestamp without time zone
user_sessions	last_visit	timestamp without time zone
user_sessions	visit_count	integer
user_sessions	is_converted	boolean
user_sessions	conversion_event	character varying
user_sessions	conversion_timestamp	timestamp without time zone
user_sessions	created_at	timestamp without time zone
user_sessions	updated_at	timestamp without time zone
uso_recursos	id_uso	integer
uso_recursos	id_restaurante	integer
uso_recursos	id_plan	integer
uso_recursos	productos_actuales	integer
uso_recursos	usuarios_actuales	integer
uso_recursos	sucursales_actuales	integer
uso_recursos	transacciones_mes_actual	integer
uso_recursos	almacenamiento_usado_mb	integer
uso_recursos	mes_medicion	integer
uso_recursos	año_medicion	integer
uso_recursos	created_at	timestamp without time zone
uso_recursos	updated_at	timestamp without time zone
usuarios	id_usuario	integer
usuarios	nombre	character varying
usuarios	email	character varying
usuarios	password_hash	character varying
usuarios	rol_id	integer
usuarios	id_sucursal	integer
usuarios	activo	boolean
usuarios	creado_en	timestamp without time zone
usuarios	actualizado_en	timestamp without time zone
v_integrity_monitoring	table_name	text
v_integrity_monitoring	total_records	bigint
v_integrity_monitoring	active_mesas	bigint
v_integrity_monitoring	free_mesas	bigint
v_integrity_monitoring	total_acumulado	numeric
vendedores	id_vendedor	integer
vendedores	nombre	character varying
vendedores	username	character varying
vendedores	email	character varying
vendedores	password_hash	character varying
vendedores	rol	character varying
vendedores	activo	boolean
vendedores	created_at	timestamp without time zone
vendedores	id_sucursal	integer
vendedores	id_restaurante	integer
vendedores	rol_admin_id	integer
ventas	id_venta	integer
ventas	fecha	timestamp without time zone
ventas	id_vendedor	integer
ventas	id_pago	integer
ventas	id_sucursal	integer
ventas	tipo_servicio	character varying
ventas	total	numeric
ventas	mesa_numero	integer
ventas	created_at	timestamp without time zone
ventas	estado	character varying
ventas	id_restaurante	integer
ventas	id_mesa	integer
ventas	tipo_pago	character varying
ventas	id_pago_final	integer
ventas	fecha_pago_final	timestamp without time zone
ventas	estado_pago	character varying
vista_lotes_criticos	id_lote	integer
vista_lotes_criticos	numero_lote	character varying
vista_lotes_criticos	producto_nombre	character varying
vista_lotes_criticos	categoria_nombre	character varying
vista_lotes_criticos	cantidad_actual	numeric
vista_lotes_criticos	fecha_caducidad	date
vista_lotes_criticos	precio_compra	numeric
vista_lotes_criticos	estado_caducidad	text
vista_lotes_criticos	estado_stock	text
vista_lotes_criticos	dias_vencido	integer
vista_lotes_criticos	dias_restantes	integer
vista_pagos_diferidos	id_pago_diferido	integer
vista_pagos_diferidos	id_venta	integer
vista_pagos_diferidos	mesa_numero	integer
vista_pagos_diferidos	total	numeric
vista_pagos_diferidos	tipo_servicio	character varying
vista_pagos_diferidos	fecha_creacion	timestamp without time zone
vista_pagos_diferidos	fecha_vencimiento	timestamp without time zone
vista_pagos_diferidos	estado	character varying
vista_pagos_diferidos	observaciones	text
vista_pagos_diferidos	id_restaurante	integer
vista_pagos_diferidos	estado_real	character varying
vista_pagos_diferidos	dias_pendiente	integer
vista_resumen_inventario	id_producto	integer
vista_resumen_inventario	producto_nombre	character varying
vista_resumen_inventario	categoria_nombre	character varying
vista_resumen_inventario	stock_actual	integer
vista_resumen_inventario	precio	numeric
vista_resumen_inventario	stock_en_lotes	numeric
vista_resumen_inventario	total_lotes	bigint
vista_resumen_inventario	lotes_vencidos	bigint
vista_resumen_inventario	lotes_por_vencer	bigint
vista_resumen_inventario	proxima_caducidad	date
vista_resumen_inventario	estado_stock	text